### ISSUE TITLE
Eslint failures in typescript typings in published lib

### ISSUE THREAD

**Issue by atomicleopard** [mattrglobal/http-signatures#54]
Thanks for the great package, HTTP signatures are hard work with much tearing of hair out, so this library as been very helpful.

I'm using the current version (4.0.1) in a typescript project, NestJS / Node based.

After adding the dependency, while linting with eslint, I get lint errors out of this project. 

```
../node_modules/@mattrglobal/http-signatures/lib/common/cryptoPrimatives.d.ts:3:32 - error TS2307: Cannot find module 'src/sign' or its corresponding type declarations.
3 import { AlgorithmTypes } from "src/sign";
                                 ~~~~~~~~~~

../node_modules/@mattrglobal/http-signatures/lib/verify/verifyRequest.d.ts:4:30 - error TS2307: Cannot find module 'src/common' or its corresponding type declarations.
4 import { VerifyResult } from "src/common";
                               ~~~~~~~~~~~~

../node_modules/@mattrglobal/http-signatures/lib/verify/verifySignatureHeader.d.ts:4:32 - error TS2307: Cannot find module 'src/sign' or its corresponding type declarations.
4 import { AlgorithmTypes } from "src/sign";
                                 ~~~~~~~~~~
```

I pulled down the repo and built it locally to try to submit a PR with a fix, but locally these files build into lib as I expect, so I am unsure what has caused this.

i.e. off `master` when I run build I get the below as expected

```
3 import { AlgorithmTypes } from ".../sign";
```

For now, I'm progressing using `patch-package` but thought I would raise with the team in case there is some part of your build or release pipeline that is contributing to this.

**Comment by kenhuang** [comment]
thanks for reporting issues, can use 4.1.0 release 🙏
